# Generated by Django 5.2.2 on 2025-07-23 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("first_name", models.CharField(max_length=255, null=True)),
                ("last_name", models.CharField(max_length=255)),
                ("info", models.TextField(blank=True, null=True)),
                ("dob", models.DateField(blank=True, null=True)),
                ("mobile", models.CharField(blank=True, max_length=13, null=True)),
                ("phone", models.CharField(blank=True, max_length=13, null=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("address", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
    ]
