# Generated by Django 5.2.1 on 2025-05-24 20:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserUploadedFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        help_text="The user-uploaded file for model training.",
                        upload_to="uploads/files/",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="A brief description of the file and its purpose for training.",
                        null=True,
                    ),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="The date and time when the file was uploaded.",
                    ),
                ),
                (
                    "file_type",
                    models.CharField(
                        blank=True,
                        help_text="The type of the file (e.g., CSV, JSON, Image, Text).",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="The user who uploaded this file.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="uploaded_files",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AIModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "job_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "model_type",
                    models.CharField(
                        choices=[
                            ("classification", "Classification"),
                            ("regression", "Regression"),
                            ("object_detection", "Object Detection"),
                            ("nlp_generation", "Natural Language Generation"),
                            ("clustering", "Clustering"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "training_parameters",
                    models.JSONField(
                        default=dict,
                        help_text="JSON field for training parameters (e.g., epochs, learning_rate, model_arch).",
                    ),
                ),
                (
                    "evaluation_metrics_target",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="JSON field for target evaluation metrics (e.g., {'accuracy': 0.9}).",
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "trained_model_artifact",
                    models.FileField(
                        blank=True, null=True, upload_to="trained_models/"
                    ),
                ),
                (
                    "training_results",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="JSON field for training results and evaluation scores.",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="custom_models",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "training_data",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="model_configurations",
                        to="machinelearning.useruploadedfile",
                    ),
                ),
            ],
        ),
    ]
