# Generated by Django 5.2.1 on 2025-05-25 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("machinelearning", "0002_apicredential_aimodel_api_key"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aimodel",
            name="model_type",
            field=models.CharField(
                choices=[
                    ("classification", "Classification"),
                    ("regression", "Regression"),
                    ("nlp_generation", "Natural Language Generation"),
                    ("other", "Other"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="apicredential",
            name="key",
            field=models.CharField(
                help_text="A unique key provided by the API service provider.",
                max_length=255,
                unique=True,
            ),
        ),
    ]
