# Generated by Django 5.2.1 on 2025-05-22 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Lead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("phone", models.CharField(blank=True, max_length=20, null=True)),
                ("company", models.CharField(blank=True, max_length=255, null=True)),
                ("address", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("website", "Website"),
                            ("cold_call", "Cold Call"),
                            ("referral", "Referral"),
                            ("social_media", "Social Media"),
                            ("ad_campaign", "Ad Campaign"),
                            ("event", "Event"),
                            ("other", "Other"),
                        ],
                        default="website",
                        max_length=50,
                    ),
                ),
                (
                    "interested_in",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("ai_voice_bot", "AI Voice Bot"),
                            ("appointment_booking", "Appointment Booking"),
                            ("customer_support", "Customer Support"),
                            ("ivr_system", "IVR System"),
                            ("custom_solution", "Custom Solution"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("contacted", "Contacted"),
                            ("qualified", "Qualified"),
                            ("converted", "Converted"),
                            ("lost", "Lost"),
                        ],
                        default="new",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
